### ISSUE TITLE
Remote object does not recognize selector: 'currentSpaceNumber'

### ISSUE THREAD

**Issue by richarddewit** [binaryage/totalspaces-api#3]
Communication between Ruby and Obj-C seems a bit broken:

> 2016-07-18 08:47:04.591 ruby[32136:112153] Communication error with TotalSpaces **\* -[NSDistantObject methodSignatureForSelector:]: remote object does not recognize selector: 'currentSpaceNumber'

**Comment by bumper314** [comment]
OS X version and TotalSpaces version? Also, are you using anything like `brew` which might change your ruby version?

**Comment by richarddewit** [comment]
Oh right, of course.

OS X Yosemite v10.10.5
TotalSpaces2 v2.3.9
totalspaces gem v0.3
ruby v2.0.0p481

I am using `brew` but not for ruby.

**Comment by sdsykes** [comment]
Try the latest gem for TotalSpaces2:
https://rubygems.org/gems/totalspaces2/versions/2.2.1

**Comment by richarddewit** [comment]
Oh I see now, this repo is the api for TotalSpaces (not 2!)
I need this: https://github.com/binaryage/totalspaces2-api/tree/master/ruby

Thanks!

Maybe you could add a link to the api on the website to prevent confusion?
